FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install

COPY . .

RUN pnpm run db:generate
RUN pnpm run build

EXPOSE 8080

CMD [ "pnpm","run", "start:backend" ]