FROM node:20-alpine

RUN npm install -g pnpm@9.0.0

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json

COPY ./apps ./apps

RUN pnpm install

RUN pnpm run db:generate
RUN pnpm turbo run build --filter=http-backend

EXPOSE 8080

CMD [ "pnpm","run", "start:backend" ]