FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json

COPY ./apps ./apps

RUN pnpm install

RUN pnpm run db:generate
RUN pnpm turbo run build --filter=frontend

EXPOSE 3000

CMD [ "pnpm", "run",  "start:frontend" ]