name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/frontend/**'
      - 'packages/**'
      - 'docker/Dockerfile.frontend'
      - '.github/workflows/cd_frontend.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          build-args: |
            NEXT_PUBLIC_HTTP_BACKEND_URL=http://${{ secrets.EC2_HOST }}:8080
            NEXT_PUBLIC_WS_URL=ws://${{ secrets.EC2_HOST }}:8081
          tags: |
            madhavsingh203/figment/figment-frontend:${{ github.sha }}
            madhavsingh203/figment/figment-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/draw-app
            docker compose pull frontend
            docker compose up -d frontend
            docker image prune -f

