## Build the docker image 
name: Deploy the Websocket
on:
  push:
    branches: [ main ]
  jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

## Push the image to docker hub

      - name: Build and Push
        uses: docker/build-push-action@v5 
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: | 
            madhav-relish/figment-ws:${{ github.sha }}
            madhav-relish/figment-ws:latest

## SSH into VM and start new image